sudo: false
language: node_js
node_js:
- '5'
- '6'
- '7'
- '8'
- '9
before_install:
- git fetch --unshallow
script:
- "/bin/bash .travis/lint-commits.sh"
- yarn run lint && yarn run coverage
after_script:
- "/bin/bash .travis/after-script.sh"
after_success:
- "/bin/bash .travis/after-success.sh"
git:
  depth: 1
cache:
  directories:
  - node_modules
notifications:
  email: false
branches:
  except:
  - /^v\d+\.\d+\.\d+$/